# Generated by Django 5.2.10 on 2026-01-23 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tên danh mục"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Mô tả")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Kích hoạt"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
            ],
            options={
                "verbose_name": "Danh mục",
                "verbose_name_plural": "Danh mục",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("description", models.TextField(verbose_name="Mô tả")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="courses/", verbose_name="Hình ảnh"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nháp"),
                            ("pending", "Chờ duyệt"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Từ chối"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="courses.category",
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Khóa học",
                "verbose_name_plural": "Khóa học",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_course", "Có thể duyệt khóa học"),
                    ("can_reject_course", "Có thể từ chối khóa học"),
                ],
            },
        ),
    ]
