# Generated by Django 5.2.11 on 2026-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Phản hồi từ Admin'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Hiển thị công khai'),
        ),
    ]
