# Generated by Django 5.2.10 on 2026-03-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_review_admin_reply_review_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Ảnh đính kèm'),
        ),
    ]
