# Generated by Django 5.2.10 on 2026-03-02 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_review_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('course_manager', 'Quản lý khóa học'), ('enrollment_manager', 'Quản lý đăng ký'), ('review_manager', 'Quản lý đánh giá'), ('content_manager', 'Quản lý nội dung'), ('super_staff', 'Nhân viên cấp cao')], max_length=50, verbose_name='Vai trò')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Bộ phận')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='Ngày vào làm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản người dùng')),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân viên',
                'verbose_name_plural': 'Hồ sơ nhân viên',
                'permissions': [('can_manage_courses', 'Có thể quản lý khóa học'), ('can_manage_enrollments', 'Có thể quản lý đăng ký học'), ('can_manage_reviews', 'Có thể quản lý đánh giá'), ('can_manage_content', 'Có thể quản lý nội dung'), ('can_view_reports', 'Có thể xem báo cáo')],
            },
        ),
    ]
