# Generated by Django 5.2.10 on 2026-03-02 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_staffprofile'),
    ]

    operations = [
    ]
